version: '3.9'
services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    environment:
      - DD_SITE=datadoghq.com
      - DD_API_KEY=<add-api-key-here>
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver